### ISSUE TITLE
Add Osmocom projects

### ISSUE THREAD

**Issue by axilirator** [cn0xroot/RFSec-ToolKit#1]
I think, it would be good to mention some Osmocom projects too:

 - OsmocomBB - MS side GSM stack implementation with sniffing (see https://youtu.be/fH_fXSr-FhU), protocol fuzzing (see https://youtu.be/7tc4hD7ckZY) and network security analysis (see https://youtu.be/9cBJV3yTaQo) capabilities. Moreover, allows researcher to turn a compatible phone into a BTS (aka CalypsoBTS, see https://youtu.be/xFjVcxMpA6c).
 - OpenBSC & OsmoBTS - network side GSM stack implementation, which may be used as FakeBTS (aka IMSI Catcher), phone fuzzing (see https://www.youtube.com/watch?v=oGPOscdLPFQ and https://www.youtube.com/watch?v=J-lUL3E-uPc).

Also, there are two SAT communications related projects:
 - osmo-tetra
 - osmo-gmr

More talks:
https://youtu.be/hsKvdga2eQg
https://youtu.be/BSW-V94uZZQ
https://youtu.be/ROppOLeB6_I

**Comment by cn0xroot** [comment]
good ideal，I'll add this to next version.thanks!

**Comment by cn0xroot** [comment]
done
