### ISSUE TITLE
ZIgbee

### ISSUE THREAD

**Issue by tellmenot** [cn0xroot/RFSec-ToolKit#10]
Here are some of the useful resource for zigbee, This might be useful for security researchers like us
zigator: https://github.com/akestoridis/zigator
Zigbee jamming: https://www.bastibl.net/reactive-zigbee-jamming/

**Comment by uglurass** [comment]
you cant if someone decides to over come transmitting power. maybe look at
the tree but how to stop a burglar to steal very hard

**Comment by cn0xroot** [comment]
done
