### ISSUE TITLE
to do

### ISSUE THREAD

**Issue by cn0xroot** [cn0xroot/RFSec-ToolKit#4]
add RTLSDR-Scanner https://github.com/EarToEarOak/RTLSDR-Scanner

**Comment by cn0xroot** [comment]
spectavue  http://www.rfspace.com/RFSPACE/SVDownload.html  http://www.moetronix.com/files/spectravue.pdf

**Comment by bvernoux** [comment]
Please add AirSpy Hardware in SDR Resource as it is the best value for money 12bits SDR Receiver on the market for more details see https://airspy.com/products and see also open source firmware/host tools on https://github.com/airspy/airspyone_firmware and https://github.com/airspy/airspyone_host

**Comment by cn0xroot** [comment]
@bvernoux 👌
